---
- name: Install Nginx
  yum:
    name: nginx
    state: latest
  notify: Restart Nginx

- name: Start and Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Allow Http Port
  firewalld:
    port: 80/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Https Port
  firewalld:
    port: 443/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Httpd to Connect to the Network
  shell: setsebool -P httpd_can_network_connect 1
  changed_when: false

- name: Create Http Nginx Configuration
  template:
    src: kazoohttp.conf.j2
    dest: /etc/nginx/conf.d/kazoohttp.conf
  notify: Restart Nginx
  register: kazoohttp

- name: Restart Nginx Immediately
  service:
    name: nginx
    state: restarted
    enabled: yes
  when: kazoohttp.changed

- include: letsencrypt.yml
  when: kazoo_enable_lets_encrypt == True

- include: usercert.yml
  when: kazoo_enable_lets_encrypt == False

- name: Create Http Nginx Configuration
  template:
    src: kazoohttps.conf.j2
    dest: /etc/nginx/conf.d/kazoohttps.conf
  notify: Restart Nginx

- name: Install MonsterUI
  yum:
    name: monster-ui
    state: latest

- name: Create MonsterUI config.js
  template:
    src: config.js.j2
    dest: /var/www/html/monster-ui/js/config.js

