---
- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Create Nginx kazoo.conf
  template:
    src: kazoo.conf.j2
    dest: /etc/nginx/conf.d/kazoo.conf
  notify: Restart Nginx

- name: Install SSL Certificate
  copy:
    content: "{{ ssl_certificate }}"
    dest: /etc/pki/tls/certs/kazoo.crt
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx

- name: Install SSL Private Key
  copy:
    content: "{{ ssl_private_key }}"
    dest: /etc/pki/tls/private/kazoo.pem
    owner: root
    group: root
    mode: 0600
  notify: Restart Nginx

- name: Start and Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Allow Http Port
  firewalld:
    port: 80/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Https Port
  firewalld:
    port: 443/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Httpd to Connect to the Network
  shell: setsebool -P httpd_can_network_connect 1
  changed_when: false

- name: Install MonsterUI
  yum:
    name: monster-ui
    state: latest

- name: Create MonsterUI config.js
  template:
    src: config.js.j2
    dest: /var/www/html/monster-ui/js/config.js

