---
- name: Install Nginx
  yum:
    name: nginx
    state: latest
  notify: Restart Nginx

- name: Start and Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Allow Http Port
  firewalld:
    port: 80/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Https Port
  firewalld:
    port: 443/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow Httpd to Connect to the Network
  shell: setsebool -P httpd_can_network_connect 1
  changed_when: false

- name: Create Http Nginx Configuration
  template:
    src: kazoohttp.conf.j2
    dest: /etc/nginx/conf.d/kazoohttp.conf
  notify: Restart Nginx
  register: kazoohttp

- name: Restart Nginx Immediately
  service:
    name: nginx
    state: restarted
    enabled: yes
  when: kazoohttp.changed

- name: Install pyOpenSSL
  yum:
    name: pyOpenSSL
    state: latest
  when: inventory_hostname == groups['couchdb'][0]

- name: Generate Let's Encrypt RSA Key
  openssl_privatekey:
    path: /etc/pki/tls/private/letsencrypt.key
  when: inventory_hostname == groups['couchdb'][0]

- name: Generate Certificate Private Key
  openssl_privatekey:
    path: /etc/pki/tls/private/kazoo.key
  when: inventory_hostname == groups['couchdb'][0]

- name: Check for CSR
  stat:
    path: /etc/pki/tls/certs/kazoo.csr
  register: csr_file
  when: inventory_hostname == groups['couchdb'][0]

- name: Generate CSR
  command: "openssl req -new -key /etc/pki/tls/private/kazoo.key -out /etc/pki/tls/certs/kazoo.csr -subj \"/CN={{ kazoo_domain }}\""
  when: inventory_hostname == groups['couchdb'][0] and csr_file.stat.exists == False 

- name: Generate Let's Encrypt Challenge
  letsencrypt:
    account_key: /etc/pki/tls/private/letsencrypt.key
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
    csr: /etc/pki/tls/certs/kazoo.csr
    dest: /etc/pki/tls/certs/kazoo.crt
  register: letsencrypt_challenge
  when: inventory_hostname == groups['couchdb'][0]

- name: Create Let's Encrypt Challenge Directory
  file:
    path: /var/www/html/letsencrypt/.well-known/acme-challenge
    state: directory
  when: inventory_hostname == groups['couchdb'][0]

- name: Fulfill Let's Encrypt Challenge
  copy:
    dest: "/var/www/html/letsencrypt/{{ letsencrypt_challenge['challenge_data'][kazoo_domain]['http-01']['resource'] }}"
    content: "{{ letsencrypt_challenge['challenge_data'][kazoo_domain]['http-01']['resource_value'] }}"
  when: inventory_hostname == groups['couchdb'][0] and letsencrypt_challenge | changed

- name: Generate Let's Encrypt Certificate
  letsencrypt:
    account_key: /etc/pki/tls/private/letsencrypt.key
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
    csr: /etc/pki/tls/certs/kazoo.csr
    dest: /etc/pki/tls/certs/kazoo.crt
    data: "{{ letsencrypt_challenge }}"
  when: inventory_hostname == groups['couchdb'][0]

- name: Store TLS Certificate
  shell: "cat /etc/pki/tls/certs/kazoo.crt"
  register: ssl_certificate
  changed_when: false
  when: inventory_hostname == groups['couchdb'][0]
  
- name: Store TLS Private Key
  shell: "cat /etc/pki/tls/private/kazoo.key"
  register: ssl_private_key
  changed_when: false
  when: inventory_hostname == groups['couchdb'][0]

- name: Install SSL Certificate
  copy:
    content: "{{ hostvars[groups['couchdb'][0]]['ssl_certificate'].stdout }}"
    dest: /etc/pki/tls/certs/kazoo.crt
    owner: root
    group: root
    mode: 0644
  notify: Restart Nginx

- name: Install SSL Private Key
  copy:
    content: "{{ hostvars[groups['couchdb'][0]]['ssl_private_key'].stdout }}"
    dest: /etc/pki/tls/private/kazoo.key
    owner: root
    group: root
    mode: 0600
  notify: Restart Nginx

- name: Create Http Nginx Configuration
  template:
    src: kazoohttps.conf.j2
    dest: /etc/nginx/conf.d/kazoohttps.conf
  notify: Restart Nginx

- name: Install MonsterUI
  yum:
    name: monster-ui
    state: latest

- name: Create MonsterUI config.js
  template:
    src: config.js.j2
    dest: /var/www/html/monster-ui/js/config.js

